version: '3.7'
services:
  db:
    container_name: database
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD: $DB_PASSOWRD
      - POSTGRES_USER: $DB_USER
      - POSTGRES_DB: $DB_NAME
    restart: always
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    networks:
      - botnetwork
    volumes:
      - ./pgdata:/var/lib/postgresql
  bot:
    container_name: weruneda_bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db

networks:
  botnetwork:
    driver: bridge