version: '3.7'
services:
  bot:
    container_name: weruneda_bot
    build:
      context: .
    command: python app.py
    restart: always
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
    env_file:
      - ".env"
    volumes:
      - .:/src